<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Form</title>
</head>
<body>
	<div>
		<form method="post" action="./simpan_buku" enctype="multipart/form-data">
			<div><textarea name="sinopsis"></textarea></div>
			<div><input type="text" name="title_book" placeholder="title book"></div>
			<div><input type="text" name="code_book" placeholder="code book"></div>
			<div><input type="text" name="price" placeholder="price"></div>
			<div><input type="text" name="author" placeholder="author"></div>
			<div><input type="text" name="publisher" placeholder="publisher"></div>
			<div><input type="text" name="stock" placeholder="stock"></div>
			<div><input type="file" name="uploads" placeholder="uploads"></div>
			<div><button>Simpan</button></div>
		</form>
	</div>
</body>
</html>